<a href="https://colab.research.google.com/github/VAIBHAVPATEL97/Udacity-ML-with-TF/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy - Dataquest Course
NumPy is very popular because it makes writing programs easy. Python is a high-level language, which means you don't have to allocate memory manually. With low-level languages, you have to define memory allocation and processing, which gives you more control over performance, but it also slows down your programming. NumPy gives you the best of both worlds: processing performance without all the allocation.

# Introduction to Ndarray
The core data structure in NumPy is the ndarray or n-dimensional array. In programming, array describes a collection of elements, similar to a list. The word n-dimensional refers to the fact that ndarrays can have one or more dimensions. We'll start by working with one-dimensional (1D) ndarrays. Cell below shows how to create a numpy array.

![image.png]()

In [1]:
import numpy as np      #import the package
ndarray = np.array([2,2,1])
print(ndarray, type(ndarray))

[2 2 1] <class 'numpy.ndarray'>

#Understanding Vectorization

Vectorization is the concept of making the processing of the data faster. Vectorization is present in the numpy library which gives it faster processing as compared to the python.

Ndarrays and the NumPy library make it easier to manipulate and analyze data. Let's explore why.

Using standard Python, we might consider using lists of lists to represent datasets. While lists of lists work with small datasets, they aren't very good for larger data sets.

Let's look at an example involving two columns of data. Each row contains two numbers we want to add together. Using standard Python, we could use a list-of-lists structure to store our data, and we could use for loops to iterate over that data:

![image.png]()

In each iteration of our loop, Python turns our code into [bytecode](https://en.wikipedia.org/wiki/Bytecode), and the bytecode asks our computer's processor to add the two numbers together. Image shown below is in gif format. Computer takes 8 processing cycles to compute eght rows of our data.

![image.png]()

Our computer would take eight processor cycles to process the eight rows of our data.

The NumPy library takes advantage of a processor feature called Single Instruction Multiple Data (SIMD) to process data faster. SIMD allows a processor to perform the same operation on multiple data points in a single processor cycle:

![image.png]()

As a result, using NumPy would only take two processor cycles — making it four times faster than standard Python alone. We call this concept of replacing for loops with operations applied to multiple data points at once vectorization, and ndarrays make vectorization possible.

We'll explore how vectorization makes our code faster and easier to execute throughout this lesson. On the next screen, we'll practice converting a real-world dataset from a list of lists to an ndarray.

# NYC TAXI-AIRPORT DATASET

So far, we've only practiced creating one-dimensional ndarrays, but ndarrays can also be two-dimensional:

 ![](https://drive.google.com/uc?export=view&id=1cI5p6odjDcg5TcW-B-R7bgG2ewxB2kHx)

To explore two-dimensional (2D) ndarrays, we'll analyze New York City taxi [trip data](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page) released by the city of New York.

We'll only work with a subset of this data — approximately 90,000 yellow taxi trips to and from New York City airports between January and June 2016. Below is information about selected columns from the dataset:

pickup_year: the year of the trip
pickup_month: the month of the trip (January is 1, December is 12)
pickup_day: the day of the month of the trip
pickup_location_code: the airport or borough where the trip started
dropoff_location_code: the airport or borough where the trip ended
trip_distance: the distance of the trip in miles
trip_length: the length of the trip in seconds
fare_amount: the base fare of the trip, in dollars
total_amount: the total amount charged to the passenger, including all fees, tolls and tips
You can find information on all columns in the [dataset data dictionary](https://s3.amazonaws.com/dq-content/289/nyc_taxi_data_dictionary.md).

Our data is in a CSV file called nyc_taxis.csv. Below are the first few lines of raw data in our CSV (we're showing only the first four columns from the file to make the format easier to understand):
#### Note:  Data used during the course is from jan - july 2016. In this notebook, I have used 2021 yellow taxi trip data. They are different.
```
pickup_year,pickup_month,pickup_day,pickup_dayofweek
2016,1,1,5
2016,1,1,5
2016,1,1,5
2016,1,1,5
```
You may notice that we could also represent the data in a table form. There is table which shows the data.

Does this look familiar? Compare this table to the diagram of the 2D ndarray we saw earlier. You can picture 2D ndarrays as storing data like this table.

To convert the dataset into a 2D ndarray, we'll first use Python's built-in csv module to import our CSV as a "list of lists." Then, we'll convert the list of lists to a ndarray. We'll again use the numpy.array() constructor, but to create a 2D ndarray, we'll pass in our list of lists instead of a single list:

```
# our list of lists is stored as data_list
data_ndarray = np.array(data_list)
```
Let's convert our taxi CSV into a NumPy ndarray!

*Exercise:*
In the script.py code box on the right, we have used Python's csv module to import the nyc_taxis.csv file and convert it to a list of lists containing float values.

Add a line of code using the numpy.array() constructor to convert the converted_taxi_list variable to a NumPy ndarray.
Assign the result to the variable name taxi.

In [ ]:
# Course exercise
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
import numpy as np
taxi = np.array(converted_taxi_list)

In [15]:
# my exercise 

# Traditional Method of converting the csv dataset to the list of list
import csv
import numpy as np

f = open('/content/Boston.csv','r')  #boston housing dataset kaggle
csv_content = list(csv.reader(f))
#print(csv_content)  # data from the csv file is saved on list of list
#print(type(csv_content), csv_content[0][1]) # list of list and print any row for understanding

#remove the first row and convert the values to float
new_csv_list =  csv_content[1:]  # taking 1 to last row and remember list starts from zero
#print(new_csv_list)

new_float = []
for row in new_csv_list:
  new_row = []
  for value in row:
    new_row.append(float(value))
  new_float.append(new_row)

# Numpy style - Convert list of list style data to ndarray
import numpy as np
ndarray = np.array(new_float)
print(type(new_float),type(ndarray))   # shows the data type of the before and after conversion

<class 'list'> <class 'numpy.ndarray'>

# Array Shapes
Let's look at the data in the taxi variable from the previous screen by printing it using Python's print() function:

```
print(taxi)

[[  2016      1      1 ...  11.65  69.99      1]
 [  2016      1      1 ...      8   54.3      1]
 [  2016      1      1 ...      0   37.8      2]
 ...
 [  2016      6     30 ...      5  63.34      1]
 [  2016      6     30 ...   8.95  44.75      1]
 [  2016      6     30 ...      0  54.84      2]]
 ```
 The ellipses (...) between rows and columns indicate that there is more data in our NumPy ndarray than can easily be printed.

However, it's often useful to know the number of rows and columns in a ndarray. When we can't easily print the entire ndarray, we can use the ndarray.shape attribute instead:

```
data_ndarray = np.array([[5, 10, 15], 
                         [20, 25, 30]])
print(data_ndarray.shape)

>>> (2, 3)

```
The data type returned is called a tuple. Tuples are very similar to Python lists, but you can't modify them.

The output gives us a few important pieces of information:

The first number tells us that there are two rows in data_ndarray.
The second number tells us that there are three columns in data_ndarray.
Next, let's confirm the number of number of rows and columns in our dataset.

In [16]:
shape_array =  ndarray.shape
print(shape_array)

(506, 15)

# Selecting and Slicing Rows and Items from Ndarrays
Next, let's compare working with ndarrays and list of lists to select one or more rows of data:
![](https://drive.google.com/uc?export=view&id=1_iUPujH76aYv9jEEi5jgCGZBfTrnNOOO)

As we see above, we can select rows in ndarrays very similarly to lists of lists. In reality, what we're seeing is a kind of shortcut. For any 2D array, the full syntax for selecting data is the following:

```
ndarray[row_index,column_index]

# or if you want to select all
# columns for a given set of rows
ndarray[row_index]
```
. . . where row_index defines the location along the row axis and column_index defines the location along the column axis.

Like lists, array slicing is from the first specified index up to — but not including — the second specified index. For example, to select the items at index 1, 2, and 3, we'd need to use the slice [1:4].

This is how we select a single item from a 2D ndarray:
![](https://drive.google.com/uc?export=view&id=1dBq9RlFr73IFM-0qYBf5tuUhMEjZxOgs)

With a list of lists, we use two separate pairs of square brackets back-to-back. With a NumPy ndarray, we use a single pair of brackets with comma-separated row and column locations.

Let's practice selecting one row, multiple rows, and single items from our taxi ndarray.

#Selecting Columns and Custom Slicing Ndarrays

Let's continue by learning how to select one or more columns of data:
![](https://drive.google.com/uc?export=view&id=1XOnvpSMGEtxnyWFcJ7WPLxeI0MWmb6BL)

With a list of lists, we need to use a for loop to extract specific column(s) and append them back to a new list. With ndarrays, the process is much simpler. We again use single brackets with comma-separated row and column locations, but we use a colon (:) for the row locations, which gives us all of the rows.

If we want to select a partial 1D slice of a row or column, we can combine a single value for one dimension with a slice for the other dimension:
![](https://drive.google.com/uc?export=view&id=1ycilvBsaiHNAbgK_ue0GTAdp4suMrGl5)

![](https://drive.google.com/uc?export=view&id=1bbISOaMQ9g-5dA2j-Dmn22WdwEgJ7X_W)

Lastly, if we want to select a 2D slice, we can use slices for both dimensions:
![](https://drive.google.com/uc?export=view&id=1ElYAl0o_UXNwQV0isfNSRvdStlJRmaqz)

Let's practice everything we've learned so far to perform some more complex selections using NumPy.

#Vector Math
As we saw on the previous two screens, NumPy ndarrays allow us to select data much more easily. Beyond this, the selection is much faster when working with vectorized operations because the operations apply to multiple data points at once.

When we first talked about vectorized operations, we used the example of adding two columns of data. With data in a list of lists, we'd have to construct a for-loop and add each pair of values from each row individually:
![](https://drive.google.com/uc?export=view&id=1CPtilBHne6a-e11-AswDpwzk3PxOeUoQ)

At the time, we only talked about how vectorized operations make this faster; however, vectorized operations also make our code easier to execute. Here's how we would perform the same task above with vectorized operations:

```
# convert the list of lists to an ndarray
my_numbers = np.array(my_numbers)

# select each of the columns - the result
# of each will be a 1D ndarray
col1 = my_numbers[:,0]
col2 = my_numbers[:,1]

# add the two columns
sums = col1 + col2
```
We could simplify this further if we wanted to:

```
sums = my_numbers[:,0] + my_numbers[:,1]
```

Here are some key observations about this code:

When we selected each column, we used the syntax ndarray[:,c] where c is the column index we wanted to select. Like we saw in the previous screen, the colon selects all rows.
To add the two 1D ndarrays, col1 and col2, we simply use the addition operator (+) between them.
Here's what happened behind the scenes:

![](https://drive.google.com/uc?export=view&id=1Zz6qDtPR0TR7TDPPOqE96KdurjuPZTeF)

The result of adding two 1D ndarrays is a 1D ndarray of the same shape (or dimensions) as the original. In this context, we can also call ndarrays vectors, a term from linear algebra. We call adding two vectors together vector addition.

*Exercise*
Use vector addition to add fare_amount and fees_amount. Assign the result to fare_and_fees.
After you run your code, use the variable inspector below the code box to inspect the variables.

In [ ]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]

fare_and_fees = fare_amount + fees_amount

#Vector Math (Continued)
On the previous screen, we used vector addition to add two columns (or vectors) together. We can actually use any of the standard Python numeric operators with vectors, including the following:

vector_a + vector_b — addition
vector_a - vector_b — subtraction
vector_a * vector_b — multiplication (this is unrelated to the vector multiplication used in linear algebra).
vector_a / vector_b - division
When we perform these operations on two 1D vectors, both vectors must have the same shape.

Let's look at another example from our taxi data set. Here are the first five rows of two of the columns in the data set:

![](https://drive.google.com/uc?export=view&id=1fhU6iVBqnQsOc_ey8a93RiHBCwwf13Ro)

Let's use these columns to calculate the average travel speed of each trip in miles per hour. This is the formula for calculating miles per hour:
```
miles per hour  = distance in miles ÷ length in hours
```
As we learned earlier in this lesson, trip_distance is already expressed in miles, buttrip_length is expressed in seconds. First, we'll convert trip_length into hours:
```

trip_distance = taxi[:,7]
trip_length_seconds = taxi[:,8]
​
trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour
```

In this case, we divided each value in the vector by a single number, 3600, instead of another vector. Below are the first five rows of the result:
```
trip_length_hours
0.565833
0.422222
0.406111
0.336111
0.210833
```
Let's perform vector division again to calculate the miles per hour.
1. Use vector division to divide trip_distance_miles by trip_length_hours. Assign the result to trip_mph.
2. After you run your code, use the variable inspector below the code box to inspect the contents of the new trip_mph variable.

In [ ]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles/trip_length_hours

# Calculating Statistics for 1D Ndarrays (Continued)

On the previous screen, we created trip_mph, a 1D ndarray of the average mile-per-hour speed of each trip in our dataset. Next, we'll explore this data further and calculate the minimum, maximum, and mean values for trip_mph.

To calculate the minimum value of a 1D ndarray, we use the vectorized ndarray.min() method, like this:

```
mph_min = trip_mph.min()
print(mph_min)

>>> 0.0
```
The minimum value in our trip_mph ndarray is 0.0 — for a trip that didn't travel any distance at all.

NumPy ndarrays have methods for many different calculations. Here are a few of the key methods:



*   ndarray.min() to [calculate the minimum value](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.min.html#numpy.ndarray.min)
*   ndarray.max() to calculate the maximum value
*   ndarray.mean() to [calculate the mean or average value](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.mean.html#numpy.ndarray.mean)
*   ndarray.sum() to [calculate the sum of the values](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.sum.html#numpy.ndarray.sum)


You can see the full list of ndarray methods in the [NumPy ndarray documentation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.ndarray.html#calculation).

It's important to become familiar with the documentation because it's not possible to remember the syntax for every variation of every data science library. However, if you remember what is possible and can read the documentation, you'll always be able to refamiliarize yourself with it when you need to.

Whenever you see the syntax ndarray.method_name(), substitute ndarray with the name of your ndarray (in this case, trip_mph) like this:

![](https://drive.google.com/uc?export=view&id=1ig2VQmVU7wYoC3JcaM6Lm1BFXkTd2Ka3)

Let's use what we've just learned to calculate the maximum and mean (average) speed from our trip_mph ndarray.

```
1. Use the ndarray.max() method to calculate the maximum value of trip_mph. Assign the result to mph_max.

2. Use the ndarray.mean() method to calculate the average value of trip_mph. Assign the result to mph_mean.
```

In [ ]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

# Calculating Statistics for 1D Ndarrays (Continued)

Looking at the result of the code on the previous screen, we can see the following:

* Average (mean) trip speed (rounded): 170 mph
* Maximum trip speed (rounded): 82,000 mph

A trip speed of 82,000 mph is definitely not possible in New York traffic — that's almost 20x faster than the fastest plane in the world! And the average trip speed of 170 mph is also not possible. These results could be due to errors in the devices that record the data, or perhaps errors made somewhere in the data pipeline.

Before we look at other array methods, let's review the difference between methods and functions. Functions act as stand alone segments of code that usually take an input, perform some processing, and return some output. For example, we can use the len() function to calculate the length of a list or the number of characters in a string.

```
my_list = [21,14,91]
print(len(my_list))
>>> 3

my_string = 'Dataquest'
print(len(my_string))
>>> 9
```
By contrast, methods are special functions that belong to a specific type of object. This means that, for instance, when we work with list objects, there are special functions or methods that we can only use with lists. For example, we can use the list.append() method to add an item to the end of a list. If we try to use that method on a string, we will get an error, like this:

```

my_string.append(' is the best!')
>>>
Traceback (most recent call last):
    File "stdin", line 1, in module
AttributeError: 'str' object has no attribute 'append'
```
![](https://drive.google.com/uc?export=view&id=19pg8n5_W8TCVUPYRaoy4v7QimEl_rnhN)

To remember the right terminology, anything that starts with np (e.g., np.mean()) is a function, and anything expressed with an object (or variable) name first (e.g., trip_mph.mean()) is a method. When both exist, it's up to you to decide which to use, but it's much more common to use the method approach.

# Calculating Statistics for 2D Ndarrays
Next, we'll calculate statistics for 2D ndarrays. If we use the ndarray.max() method on a 2D ndarray without any additional parameters, it will return a single value, just like a 1D array:
![](https://drive.google.com/uc?export=view&id=1HxyY7Eu_gT6Re7XrhFnv56QrjW5o8kvR)

But what if we want to find the maximum value of each row? We need to use the axis parameter and specify a value of 1 to indicate that we want to calculate the maximum value for each row.

![](https://drive.google.com/uc?export=view&id=1jB3zoo7BIP2LAGBmCSnVn348GlfdE7M-)

If we want to find the maximum value of each column, we'd use an axis value of 0:


![](https://drive.google.com/uc?export=view&id=1Cdc7RgifSiOFtC3qNCI-dp3fpKNc3TRO)

Let's use what we've learned to check the data in our taxi dataset. To remind ourselves how the data looks, let's examine the first five rows of the columns with indices 9 through 13:

Table showing the taxi dataset
```
fare_amount	fees_amount	tolls_amount	tip_amount	total_amount
52.0	0.8	5.54	11.65	69.99
45.0	1.3	0.00	8.00	54.3
36.5	1.3	0.00	0.00	37.8
26.0	1.3	0.00	5.46	32.76
17.5	1.3	0.00	0.00	18.8
```
You may have noticed that the sum of the first four values in each row should equal the last value, total_amount:

fare amount
+
fees amount
+
tolls amount
+
tip amount
=
total amount
In the next exercise, we'll check these values. We'll only review the first five rows in taxi so we can verify the results more easily.

In this lesson, we learned the following:

* How vectorization speeds up our code
About n-dimensional arrays, and NumPy's ndarrays
* How to select specific items, rows, columns, 1D slices, and 2D slices from ndarrays
* How to apply simple calculations to entire ndarrays
* How to use vectorized methods to perform calculations across either axis of ndarrays

In the next lesson, we'll continue to work with the NYC taxi data as we learn about Boolean indexing, one of the most powerful tools when working with data in NumPy and pandas.

*Numpy Cheatsheet SS in gdrive.*

# Boolean Indexing with NumPy - Lesson 2

## 1. Reading CSV files with NumPy

NumPy makes it easy to select data, and it includes a number of functions that simplify calculating statistics across the different axes (or dimensions).

For example, let's say we want to find out how many taxi trips riders took each month? Or which airport is the busiest? For this, we will learn a new technique: Boolean Indexing. Before we get started with Boolean Indexing, let's look at our data.
Here are the first five rows of our data with column labels: (dataset table image - not attached)


Below is information about selected columns from the dataset:
You can find information on all columns in the [data dictionary](https://s3.amazonaws.com/dq-content/290/nyc_taxi_data_dictionary.md).

Now, let's learn how to use the numpy.genfromtxt() function to read files into NumPy ndarrays. Here is the simplified syntax for the function, and an explanation of the two parameters:

```
np.genfromtxt(filename, delimiter=None)
```
* filename: a positional argument, usually a string representing the path to the text file to read
* delimiter: a named argument, specifying the string used to separate each value

In this case, because we have a CSV file, the delimiter is a comma. Here's how we'd read in a file named data.csv:

```
data = np.genfromtxt('data.csv', delimiter=',')
```
Let's read our nyc_taxis.csv file into NumPy next.

In [ ]:
import numpy as np
taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',')
taxi_shape =  taxi.shape

# 2.Reading CSV Files with NumPy Continued
In the previous exercise, we used the numpy.genfromtxt() function to read the nyc_taxis.csv file into NumPy, which allowed us to import the data quickly and efficiently:

```
# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi = np.array(converted_taxi_list)
```
We convert all the values to floats before we convert the list of lists to a ndarray. That's because NumPy ndarrays can contain only one datatype.

We didn't have to complete this step in the previous exercise because when numpy.genfromtxt() reads in a file, it attempts to determine the data type of the file by looking at the values.

We can use the ndarray.dtype attribute to see the internal datatype.

```
print(taxi.dtype)
>>> float64
```
NumPy chose the float64 type, since it will allow most of the values from our CSV to be read. You can think of NumPy's float64 type as identical to Python's float type (the "64" refers to the number of bits used to store the underlying value).

If we review the results from the previous exercise, we can see that taxi contains almost all numbers except for a value that we haven't seen before: nan.


```
[[   nan    nan    nan ...,    nan    nan    nan]
 [  2016      1      1 ...,  11.65  69.99      1]
 [  2016      1      1 ...,      8   54.3      1]
 ..., 
 [  2016      6     30 ...,      5  63.34      1]
 [  2016      6     30 ...,   8.95  44.75      1]
 [  2016      6     30 ...,      0  54.84      2]]
 ```
 NaN is an acronym for Not a Number — it literally means that the value cannot be stored as a number. It is similar to (and often referred to as a) null value, like Python's None constant.

We most commonly see NaN when a value is missing, but in this case, we have NaN values because the first line from our CSV file contains the names of each column. NumPy is unable to convert string values like pickup_year into the float64 data type.

For now, we need to remove this header row from our ndarray. We can do this the same way we would if our data was in a list of lists:

```
taxi = taxi[1:]
```
Alternatively, we can pass an additional parameter, skip_header, to the numpy.genfromtxt() function. The skip_header parameter accepts an integer — the number of rows from the start of the file to skip. Note that because this integer should be the number of rows and not the index, skipping the first row would require a value of 1, not 0.]

```
Instructions

Use the numpy.genfromtxt() function to again read the nyc_taxis.csv file into NumPy, but this time, skip the first row. Assign the result to taxi.
Assign the shape of taxi to taxi_shape.
Use the variable inspector under the code box to view the taxi ndarray and its shape after you have run your code
```

In [ ]:
import numpy as np
#taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',')
#taxi = taxi[1:]     # 1st method to remove header of the csv file
taxi = np.genfromtxt('nyc_taxis.csv', delimiter = ',', skip_header = 1) # 2nd method to remove header from csv 
taxi_shape = taxi.shape

# 3. Boolean Arrays
Now, let's focus on arguably the most powerful method to index data: the Boolean array. A Boolean array, as the name suggests, is an array of Boolean values. We sometimes call Boolean arrays Boolean vectors or Boolean masks.

You may recall that the Boolean (or bool) type is a built-in Python type that can be one of two unique values:

True
False
We also use Boolean values when working with Python comparison operators like == (equal) > (greater than), < (less than), != (not equal). Below are some examples of simple Boolean operations:
We also use Boolean values when working with Python comparison operators like == (equal) > (greater than), < (less than), != (not equal). Below are some examples of simple Boolean operations:

```
print(type(3.5) == float)
>> True
print(5 > 6)
>>> False
```
When we're talking about vector math, an operation between a ndarray and a single value results in a new ndarray:

```
print(np.array([2,4,6,8]) + 10)
[12 14 16 18]
```
The + 10 operation applies to each value in the array.

Now, let's look at what happens when we perform a Boolean operation between an ndarray and a single value:

```
print(np.array([2,4,6,8]) < 5)
[ True  True False False]
```
A similar pattern occurs – each value in the array is compared to five. If the value is less than five, True is returned. Otherwise, False is returned.

![](https://drive.google.com/uc?export=view&id=1kP7epVRK9i0qnDpXKBvzYipZnZJ4-Fy3)

Let's practice using vectorized Boolean operations to create some Boolean arrays.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])
a_bool = a < 3
b_bool = (b == "blue")
c_bool = c > 100

>>>

a_bool
ndarray (<class 'numpy.ndarray'>)
array([ True,  True, False, False, False])
b_bool
ndarray (<class 'numpy.ndarray'>)
array([ True,  True, False,  True])
c_bool
ndarray (<class 'numpy.ndarray'>)
array([False,  True, False,  True])

# 4.Boolean Indexing with 1D ndarrays
On the previous screen, we learned how to create Boolean arrays using vectorized Boolean operations. Next, we'll learn how to index (or select) using Boolean arrays, known as Boolean indexing. Let's use one of the examples from the previous screen.

![](https://drive.google.com/uc?export=view&id=18UksuqpAAKz4iRt2LXycWsOAs-Jm0b23)

To index using our new Boolean array, we simply insert it in the square brackets, just like we would do with our other selection techniques:
![](https://drive.google.com/uc?export=view&id=1ku96jDyFyT-o7Xn_hLCcTY8UX8FgBxTg)

The Boolean array acts as a filter, so that the values corresponding to True become part of the result and the values corresponding to False are removed.

Let's use Boolean indexing to confirm the number of taxi rides in our data set from the month of January. First, let's select just the pickup_month column, which is the second column in the ndarray:

```
pickup_month = taxi[:,1]
```
Next, we use a Boolean operation to make a Boolean array, where the value 1 corresponds to January:

```
january_bool = pickup_month == 1
```
Then we use the new Boolean array to select only the items from pickup_month that have a value of 1:

```
january = pickup_month[january_bool]
```
Finally, we use the .shape attribute to determine how many items are in our january ndarray, which is equal to the number of taxi rides from the month of January. We'll use [0] to extract the value from the tuple returned by .shape:


```
january_rides = january.shape[0]
print(january_rides)
>>> 800
```

There are 800 rides in our dataset from the month of January. Let's practice Boolean indexing and determine the number of rides in our data set for February.

In [ ]:
pickup_month = taxi[:,1]

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]

# 5. Boolean Indexing with 2D ndarrays
When working with 2D ndarrays, you can use Boolean indexing in combination with other indexing methods. The only limitation is that the Boolean array must have the same length as the dimension you're indexing. Let's look at some examples:
![](https://drive.google.com/uc?export=view&id=1XZeTrLXj-LsTKOc4vBm-5C74C6Np2zrz)

Because a Boolean array contains no information about its creation, we can use a Boolean array made from just one column of our array to index the entire array.

Let's use what we've learned to analyze the average speed of trips. Let's see if there are any issues with the data. We calculated the average travel speed as follows:

```
# calculate the average speed
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
```
Next, we'll check for trips with an average speed greater than 20,000 mph:

```
# create a boolean array for trips with average
# speeds greater than 20,000 mph
trip_mph_bool = trip_mph > 20000

# use the boolean array to select the rows for
# those trips, and the pickup_location_code,
# dropoff_location_code, trip_distance, and
# trip_length columns
trips_over_20000_mph = taxi[trip_mph_bool,5:9]

print(trips_over_20000_mph)


>>>
[[     2      2     23      1]
 [     2      2   19.6      1]
 [     2      2   16.7      2]
 [     3      3   17.8      2]
 [     2      2   17.2      2]
 [     3      3   16.9      3]
 [     2      2   27.1      4]]
```
We can see from the last column that most of these are very short rides — all have trip_length values of 4 seconds or fewer, which does not reconcile with the trip distances, all of which are more than 16 miles.

Let's use this technique to examine the rows that have the highest values for the tip_amount column.

```
* nCreate a Boolean array, tip_bool, that determines which rows have values for the tip_amount column of more than 50.

* Use the tip_bool array to select all rows from taxi with values tip amounts of more than 50, and the columns from indexes 5 to 13 inclusive. Assign the resulting array to top_tips.
```

In [ ]:
tip_amount = taxi[:,12]
print(tip_amount.shape)
tip_bool = tip_amount > 50
top_tips = taxi[tip_bool, 5:14]

# 6. Assigning Values in ndarrays
So far, we've learned how to retrieve data from ndarrays. Next, we'll use the same indexing techniques we've already learned to modify values within an ndarray. Here is the syntax we'll use (in pseudocode):
```
ndarray[location_of_values] = new_value
```
Let's see how that looks like in actual code. With our 1D array, we can specify one specific index location:

```
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
print(a)

>>>
['orange', 'blue', 'black', 'blue', 'purple']
```
Or we can assign multiple values at once:

```
a[3:] = 'pink'
print(a)
>>> ['orange', 'blue', 'black', 'pink', 'pink']
```
With a 2D ndarray, as with a 1D ndarray, we can assign one specific index location:

```
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2] = 99
print(ones)
>>>
[[ 1,  1,  1,  1,  1],
 [ 1,  1, 99,  1,  1],
 [ 1,  1,  1,  1,  1]]

```
We can also assign a whole row...

```
ones[0] = 42
print(ones)

>>>
[[42, 42, 42, 42, 42],
 [ 1,  1, 99,  1,  1],
 [ 1,  1,  1,  1,  1]]
```
 ...or a whole column:
```
ones[:,2] = 0
print(ones)
>>>
[[42, 42, 0, 42, 42],
 [ 1,  1, 0,  1,  1],
 [ 1,  1, 0,  1,  1]]

```
```
To help you practice without making changes to our original array, we have used the ndarray.copy() method to make taxi_modified, a copy of our original for these exercises.

1. The value at column index 5 (pickup_location) of row index 1066 is incorrect. Use assignment to change this value to 1 in the taxi_modified ndarray.
2. The first column (index 0) contains year values as four-digit numbers in the format YYYY (2016, since all trips in our dataset are from 2016). Use assignment to change these values to the YY format (16) in the taxi_modified ndarray.
3. The values at column index 7 (trip_distance) of rows index 550 and 551 are incorrect. Use assignment to change these values in the taxi_modified ndarray to the mean value for that column.
```

In [ ]:
# this creates a copy of our taxi ndarray
taxi_modified = taxi.copy()

taxi_modified[1066,5] = 1
taxi_modified[:,0] = 16
taxi_modified[550:552,7] = taxi_modified[:,7].mean()

# 7. Assignment Using Boolean Arrays
Boolean arrays become very powerful when we use them for assignment. Let's look at an example:


```

a2 = np.array([1, 2, 3, 4, 5])
a2_bool = a2 > 2
a2[a2_bool] = 99
print(a2)
>>>
[ 1  2 99 99 99]
```
The Boolean array controls the values to which the assignment applies, and the other values remain unchanged. Let's look at how this code works:
![](https://drive.google.com/uc?export=view&id=1s3O8L71G8KMeTbWdrDpHthEqHS7bgcBe)

Notice in the diagram above that we used a "shortcut" — we inserted the definition of the Boolean array directly into the selection. This "shortcut" is the conventional way to write Boolean indexing. Up until now, we've been assigning to an intermediate variable first so that the process is clear, but from now on, we will use this "shortcut" method instead.
```
We again used the ndarray.copy() method to make taxi_copy, a copy of our original for this exercise.

1. Select the fourteenth column (index 13) in taxi_copy. Assign it to a variable named total_amount.
2. or rows where the value of total_amount is less than 0, use assignment to change the value to 0.


```

In [ ]:
# this creates a copy of our taxi ndarray
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
print(total_amount.shape)

total_amount[total_amount < 0] = 0

# 8. Assignment Using Boolean Arrays Continued

Next, we'll look at an example of assignment using a Boolean array with two dimensions:
![](https://drive.google.com/uc?export=view&id=1gGrlKPRJKrxLiz1NPzwcEV0TKpWds7XQ)

The b > 4 Boolean operation produces a 2D Boolean array which then controls the values that the assignment applies to.

We can also use a 1D boolean array to perform assignment on a 2D array:

![](https://drive.google.com/uc?export=view&id=1xqkvyXFXRXlwm9VFvSgMulnpkmzMhirE)

The c[:,1] > 2 Boolean operation compares just one column's values and produces a 1D Boolean array. We then use that Boolean array as the row index for assignment, and 1 as the column index to specify the second column. Our Boolean array only applies to the second column, while all other values remain unchanged.

The pseudocode syntax for this code is as follows, first using an intermediate variable:
```
bool = array[:, column_for_comparison] == value_for_comparison
array[bool, column_for_assignment] = new_value
```
. . . and then all in one line:
```
array[array[:, column_for_comparison] == value_for_comparison, column_for_assignment] = new_value
```
Let's practice this pattern using our taxi dataset:

```
Exercise:
We have created a new copy of our taxi dataset, taxi_modified, with an additional column containing the value 0 for every row.

1. In our new column at index 15, assign the value 1 if the pickup_location_code (column index 5) corresponds to an airport location, leaving the value as 0 otherwise by performing these three operations:
For rows where the value for the column index 5 is equal to 2 (JFK Airport), assign the value 1 to column index 15.
For rows where the value for the column index 5 is equal to 3 (LaGuardia Airport), assign the value 1 to column index 15.
For rows where the value for the column index 5 is equal to 5 (Newark Airport), assign the value 1 to column index 15.

In [ ]:
# create a new column filled with `0`.
zeros = np.zeros([taxi.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)

taxi_modified[taxi_modified[:, 5] == 2, 15] = 1
taxi_modified[taxi_modified[:, 5] == 3, 15] = 1
taxi_modified[taxi_modified[:, 5] == 5, 15] = 1

# 9.Challenge: Which Is the Most Popular Airport?
We'll conclude this lesson with two challenges that will help you practice the techniques you've learned in this lesson.

We supplied several hints to help you, but first try to complete the challenge without the hints — if you can. Don't feel discouraged if these challenge steps take a few attempts – working with data is an iterative process!

In this challenge, we want to figure out which airport is the most popular destination in our dataset. To do that, we'll use Boolean indexing to create three filtered arrays and then look at how many rows are in each array.

To complete this task, we'll need to check if the dropoff_location_code column (column index 6) is equal to one of the following values:

2: JFK Airport
3: LaGuardia Airport
5: Newark Airport.

In [ ]:
jfk = taxi[taxi[:,6] == 2]
jfk_count = jfk.shape[0]

laguardia = taxi[taxi[:,6] == 3]
laguardia_count = laguardia.shape[0]

newark = taxi[taxi[:,6] == 5]
newark_count = newark.shape[0]

Our calculations on the previous screen show that LaGuardia is the most common airport for dropoffs in our dataset.

Our second and final challenge involves removing potentially bad data from our data set, and then calculating some descriptive statistics on the remaining "clean" data.

We'll start by using Boolean indexing to remove any rows that have an average speed for the trip greater than 100 mph (160 kph) which should remove any questionable data. Then, we'll use array methods to calculate the mean for specific columns of the remaining data. Here are the columns we're interested in:

* trip_distance, at column index 7
* trip_length, at column index 8
* total_amount, at column index 13

In [ ]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

cleaned_taxi = taxi[trip_mph < 100]

mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()

# In this lesson we learned the following:

* How to use numpy.genfromtxt() to read in an ndarray
* NaN values
* What a Boolean array is, and how to create one
* How to use Boolean indexing to filter values in one- and two-dimensional ndarrays
* How to assign one or more new values to an ndarray based on their locations
* How to assign one or more new values to an ndarray based on their values


This is the last lesson that deals exclusively with NumPy, but it's certainly not the last time we'll use NumPy. As we move onto learning other Python data libraries, you'll find yourself using a lot of these fundamental NumPy concepts. We'll also use NumPy from time to time to create, transform, and otherwise work with tabular data.

In the next lesson, we'll start using the pandas library and learn how it compares to NumPy.

![](https://drive.google.com/uc?export=view&id=1s2cMkeW4UQ2F3RWr-i3aCgOz0paaXCCQ)
![](https://drive.google.com/uc?export=view&id=1i1x-sQ7jqFBLapXRxtG5sOW-YJ9PreqL)
![](https://drive.google.com/uc?export=view&id=1wrTCbWwJAlO69ZTe7QO_D05NMGENokNB)
![](https://drive.google.com/uc?export=view&id=1j0OpMHS37EgD7VqqXEcDlQBuPawz9Hg1)
![](https://drive.google.com/uc?export=view&id=1BVMbHvHFa7Or5gVhWjCWqzPSyJ7JtIkl)